geekhunter/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('api/v1/', include('vacancies_app.api_urls')),
    path('', include('vacancies_app.urls')),
    path('parsers/', include('parsers_app.urls')),
    path('admin/', admin.site.urls),
    path('auth/', include('djoser.urls')),
    path('auth/', include('djoser.urls.authtoken')),
    path('stats/', include('analytics_app.urls')),
]

vacancies_app/forms.py
from django import forms
from .crud import *


class SearchForm(forms.Form):
    cities = forms.ChoiceField(choices=[(item, item) for item in cities_list()])
    specialities = forms.ChoiceField(choices=[(item, item) for item in specialities_list()])
    grades = forms.ChoiceField(choices=[(item, item) for item in grades_list()])
    experiences = forms.ChoiceField(choices=[(item, item) for item in experiences_list()])
    languages = forms.ChoiceField(choices=[(item, item) for item in languages_list()])
    is_remote = forms.BooleanField(widget=forms.CheckboxInput, required=False)
    salary_from = forms.IntegerField(
        required=False,
        widget=forms.NumberInput(attrs={'class': 'form-control', 'placeholder': 'Зарплата от...'})
    )

templates/components/lang_stats.html
{{ test }}

templates/components/search_form.html
<form action="/vacancies/" method="get" class="search-form">

    <div class="form-wrapper">

        <div class="mb-2">
            <select class='form-select' name="speciality">
                <option value=''>Специализация</option>
                {% for speciality in form.specialities %}
                {{ speciality }}
                {% endfor %}
            </select>
        </div>

        <div class="mb-2">
            <select class='form-select' name="language">
                <option value=''>Язык</option>
                {% for language in form.languages %}
                {{ language }}
                {% endfor %}
            </select>
        </div>

        <div class="mb-2">
            <select class='form-select' name="grade">
                <option value=''>Уровень</option>
                {% for grade in form.grades %}
                {{ grade }}
                {% endfor %}
            </select>
        </div>

        <div class="mb-2">
            <select class='form-select' name="experience">
                <option value=''>Опыт</option>
                {% for experience in form.experiences %}
                {{ experience }}
                {% endfor %}
            </select>
        </div>


        <div class="mb-2">
            <select class='form-select' name="location">
                <option value=''>Локация</option>
                {% for city in form.cities %}
                {{ city }}
                {% endfor %}
            </select>
        </div>

        <div class="mb-2 form-check" style="padding-left: 0;">
            <div class="remote-section">
                {{ form.is_remote }}
                <label class="form-check-label" for="id_is_remote">Можно удаленно</label>
            </div>
        </div>

        <div class="mb-2">
            {{ form.salary_from }}
        </div>

        <div class="mb-2">
            <button class="btn btn-success" type="submit" style="width: 100%">Искать</button>
        </div>

        {% if result %}
            Найдено вакансий: {{ result }}
        {% endif %}

    </div>

</form>